# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BboyTraining-iOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BboyTraining-iOS
  pod 'MSCellAccessory'  
  pod 'ionicons'  
  pod 'ZCAnimatedLabel'  

  target 'BboyTraining-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BboyTraining-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
